language: python
sudo: false
cache: pip
matrix:
  include:
    - python: "2.7"
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
         - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
before_install:
  - eval "${MATRIX_EVAL}"

install:
  - pip install -r requirements.txt
  - python setup.py build install

script: pytest test/metrics.py
